### ISSUE TITLE
Select field - Category list

### ISSUE THREAD

**Issue by x-bull** [sohan5005/ts-shortcode-generator#1]
Hi

Thist generator looks awesome and working fine. I have one question.

Is there some way how to add list of categories (post or woocommerce products) inside select and multiselect fields?

**Comment by sohan5005** [comment]
Hi

First of all, thanks for using my work :)

Yes it has that facility built in. There are some helper functions to do that. You can see the functions below.

When you want to use categories or other taxonomy:
`return_terms_for_tsg_template( $taxonomy, $id );`
By default `$taxonomy` is 'category'. You may also use your custom taxonomy. `$id` is a boolean argument. When true, you'll get term id as value, when false you will get slug.

When you want to use posts or custom post type:
`return_posts_for_tsg_template( $post_type, $id );`
By default `$post_type` is 'post'. `$id` is same as before.

For WooCommerce, use 'products' as post type and 'product_cat' or 'post_tag' for taxonomy as product category/tags and so on.

For WooCommerce product attributes:
`return_wc_attributes_for_tsg_template();`
This function will fetch directly from database as attributes are not terms generally.

There are a few more functions. You'll find them when you look at the bottom of the 'bootstrap.php' file.

For your case, attributes can be set up like this:

```
'categories' => array(
    'title' => __( 'List all categories', 'textdomain' ),
    'desc' => __( 'Description', 'textdomain' ),
    'type' => 'select',
    'vals' => return_terms_for_tsg_template(), // as default is category
),
'tags' => array(
    'title' => __( 'List all tags', 'textdomain' ),
    'desc' => __( 'Description', 'textdomain' ),
    'type' => 'select',
    'vals' => return_terms_for_tsg_template('post_tag'),
),
'posts' => array(
    'title' => __( 'List all posts', 'textdomain' ),
    'desc' => __( 'Description', 'textdomain' ),
    'type' => 'select',
    'vals' => return_posts_for_tsg_template(), // as default is posts
),
'wc_products' => array(
    'title' => __( 'List all WooCommerce products', 'textdomain' ),
    'desc' => __( 'Description', 'textdomain' ),
    'type' => 'select',
    'vals' => return_posts_for_tsg_template('product'),
),
'wc_products_cat' => array(
    'title' => __( 'List all WooCommerce product categories', 'textdomain' ),
    'desc' => __( 'Description', 'textdomain' ),
    'type' => 'select',
    'vals' => return_terms_for_tsg_template('product_cat'),
),
```

That's not all, you can use any of this function with other fields like multiselect, checkbox or radio.

Hope that helps. If you need anything else please let me know.
Thanks!

**Comment by x-bull** [comment]
Thats perfect :+1: 

After few hours I made own functions for categories and products, but if its build in, I use yours :-)

Some docs will be fine

**Comment by sohan5005** [comment]
Yes I wanted to make some docs. But couldn't get my time to do that.

I will try to make it's docs asap.

Thanks.

**Comment by x-bull** [comment]
Hi again

Sorry about opening ticket again. Are you testing the product categories function?

```
return_terms_for_tsg_template('product_cat')
```

I got errors:
Notice: Trying to get property of non-object in bootstrap.php on line 482
Notice: Trying to get property of non-object in bootstrap.php on line 483

Same when I make my own fuction. I must get the terms from database:

```
function twp_get_product_cats() {
  global $wpdb; 
  $all_categories = $wpdb->get_results('SELECT name, ' . $wpdb->prefix . 'terms.term_id FROM ' . $wpdb->prefix . 'terms, ' . $wpdb->prefix . 'term_taxonomy WHERE ' . $wpdb->prefix . 'terms.term_id = ' . $wpdb->prefix . 'term_taxonomy.term_id AND taxonomy = "product_cat" ORDER BY name ASC;');
  foreach ($all_categories as $cat) {
    $categories[] = array(
      'val' => $cat->term_id,
      'label' => $cat->name,
    );  
  }
  return $categories;
}
```

Am I do somethig worng, is your function correct? For me my function working.

**Comment by sohan5005** [comment]
It's strange that it just works fine on my side.

By default, terms that don't have any posts under it, will be ignored. You can change that by editing the function from bootstrap.php

Here: https://github.com/sohan5005/ts-shortcode-generator/blob/c3b00430a29758f1266dc92fa8cfcb651f2c1443/bootstrap.php#L478

Change this line to:
`$terms = get_terms( $tax, array( 'hide_empty' => false ) );`

By the way, you can use `get_terms()` function which is found in WordPress itself. So you don't need to use the `$wpdb` with that long line of SQL.
