### ISSUE TITLE
Select2 and ColorPicker

### ISSUE THREAD

**Issue by ThomasFx** [sohan5005/ts-shortcode-generator#2]
Hi

I am testing this great tool. But on clear WordPress instalation looks select fields ugly - is the Select2 integrated? Must be init from some plugin like WooCommerce.

Color field not working - Uncaught TypeError: selector.colorpicker is not a function (generator.js on line 493)

I never made some plugin, maybe is problem on my side.

Could you help me please?

**Comment by sohan5005** [comment]
You are right. I have forgot about those 2 things. The files are not included in the package. Maybe I forgot because any of my other plugin had them.

I'll fix them asap.

**Comment by sohan5005** [comment]
Fixed in the latest commit. Download the latest version and it will work fine.
