### ISSUE TITLE
Load only on editor

### ISSUE THREAD

**Issue by ThomasFx** [sohan5005/ts-shortcode-generator#6]
I found this generator. Perfect work.
The generator is loaded everywhere on backend. Is it possible make some load restriction only for editor?

**Comment by sohan5005** [comment]
I think there's no way to determine if current screen has wp_editor or not. But I'll find a way to do it.

**Comment by sohan5005** [comment]
Please check with the latest commit. Update the `bootstrap.php` file and let me know if that worked.

Cheers

**Comment by ThomasFx** [comment]
I was thinking about [this](https://codex.wordpress.org/Plugin_API/Action_Reference/admin_enqueue_scripts#Example:_Target_a_Specific_Admin_Page) solution

But your solution is better

**Comment by sohan5005** [comment]
That one will work too but you have to set specific screens. There may be some edge case where a custom plugin/framework page provides WP Editor. Then you'll miss that page. Also some custom post type might not support the WP Editor, that page will load the shortcode builder unnecessarily.

So I implemented the best way to do it :) Whichever page have Editor, will load this library.
