### ISSUE TITLE
Sorting issue

### ISSUE THREAD

**Issue by x-bull** [sohan5005/ts-shortcode-generator#7]
Hi
I am trying put WooCommerce products via multiselect field. My problem is, that the field ignores selected product sorting and allways print the shortcode in default sort (probably by date sorting).

My code:
```
array(
                'tag' => 'products-masonry', // The actual tag of the shortcode
                'title' => __( 'Products Masonry', 'textdomain' ),
                'desc' => __( 'Print masonry with products', 'textdomain' ),
                'selftag' => true, // if the shortcode should not contain any content
//                'icon' => 'path/to/icon',
                'icon' => 'fa-folder-open', // Font-awesome can be used
                'atts' => array(
                    'ids' => array(
                        'title' => __( 'Include products', 'textdomain' ),
                        'type' => 'multiselect',
                        'default' => false,
                        'vals' =>  return_posts_for_tsg_template( 'product' )
                    ),
                    
                ),
            ),
```

Another question. Could be the multiselect sortable?

**Comment by sohan5005** [comment]
You have to tweak it inside your shortcode. That means when you create the query or use WooCommerce functions to show products, you have to indicate the sorting. If you don't it will use the default which is always "date".

And the multiselect field is not sortable I believe. But it can be done with some additional JavaScript. Which I may add when I can give some time to this project.

Thanks for using my library!
